#cloud-config
package_update: true
package_upgrade: true
# pre update and upgrade our instance on its first boot https://docs.fuga.cloud/how-to-use-cloud-init

packages:
  - nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80;
        listen 127.0.0.1;
      }
runcmd:
  - service nginx restart
  